### ISSUE TITLE
Run example in production with docker

### ISSUE THREAD

**Issue by jenyashvartsman** [Guillembonet/single-spa-parcel-example#1]
Tried to run the example in production with docker but failing to load the React or Vue apps
![image](https://user-images.githubusercontent.com/12622345/74577098-96de7100-4f5b-11ea-9187-863530553c51.png)

another error when going to  Vue app port directly
![image](https://user-images.githubusercontent.com/12622345/74577068-7f06ed00-4f5b-11ea-94a4-3d1e364a4898.png) 

Docker version 19.03.1, build 74b1e89e8a
docker-compose version 1.24.1, build 4667896b

![image](https://user-images.githubusercontent.com/12622345/74576916-f25c2f00-4f5a-11ea-8acf-ddba409a18d1.png)

When running in development mode everything loads ok

**Comment by Guillembonet** [comment]
Hi, I'll look into it on Monday!

**Comment by Guillembonet** [comment]
The production website is running in http://localhost:5001
Sorry for the late reply, and I'll modify the readme to add this information, my bad!
