### ISSUE TITLE
Not able to run example in local machine

### ISSUE THREAD

**Issue by rakeshpccs** [Guillembonet/single-spa-parcel-example#2]
While running example on local trying to run sample-vue and sample-vue-parcel using npm run serve getting following error
 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 4 errors                                                                       4:10:19 PM

 error  in ./src/components/ParcelPage.vue

Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
> <template>
|   <div class="py-3">
|     <h1 class="h1-vue">This is a Vue App</h1>

 @ ./src/main.js 16:0-53 33:15-25
 @ multi (webpack)-dev-server/client?http://192.168.0.184:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/components/Home.vue

Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
> <template>
|   <div class="py-3">
|     <h1 class="h1-vue">This is a Vue app</h1>

 @ ./src/main.js 9:0-41 25:15-19
 @ multi (webpack)-dev-server/client?http://192.168.0.184:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/components/About.vue

Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
> <template>
|   <div class="py-3">
|     <h1 class="h1-vue">This is an About page</h1>

 @ ./src/main.js 10:0-43 29:15-20
 @ multi (webpack)-dev-server/client?http://192.168.0.184:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/App.vue

Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
> <template>
|   <div id="app">
|     <router-view class="vue-app"></router-view>

 @ ./src/main.js 7:0-28 40:15-18
 @ multi (webpack)-dev-server/client?http://192.168.0.184:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by a1285771357** [comment]
I fork the Git repository and modify the startup problem。[https://github.com/a1285771357/single-spa-parcel-example](url)

**Comment by Guillembonet** [comment]
Merged his pull request, sorry for the delay!
